project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!peer_review_word.qmd"

website:
  title: "Spatio-temporal demand and capacity relationships with performance"
  page-navigation: true
  site-path: /outputs/
  navbar:
    right:
      - icon: github
        href: https://github.com/nhs-bnssg-analytics/d_and_c
        aria-label: GitHub
  sidebar:
    logo: outputs/logo.png
    logo-href: index.html
    style: "docked"
    background: "white"
    search: true
    contents: 
      - text: "Scope"
        file: outputs/01_index.qmd
      - outputs/introduction_introduction_and_aims.qmd
      - section: Data
        contents: outputs/Data/*
      - section: Modelling
        contents: outputs/Modelling/*
      - section: Results
        contents: outputs/Results/*

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true